rspec-retry.gemspec
Fixes incompatibility with minitest/spec.
=> Update dependencies to only depend on rspec-core

README.md, lib/rspec/retry.rb, rspec-retry.gemspec, spec/lib/rspec/retry_spec.rb, spec/spec_helper.rb
Current behaviour is only changed when a (non-empty) list of Exceptions is provided as `exceptions_to_retry`, in a similar manner as the other settings are.
When that happens (and `retry` or `default_retry_count` is > 1), we check if the Exception raised on the example matches any of the provided ones and if it doesn't, we immediately fail instead of retrying.
Also piggybacked some useful changes:
- defaulted to using `pry-byebug` on Ruby 2.x
- upgraded RSpec's syntax to the "expect" format
=> Add option to restrict retries to a list of Exceptions

lib/rspec_ext/rspec_ext.rb
=> fix rspec 3.3

lib/rspec/retry.rb
The exception messages from retries are being masked unless all retries failed. So it is not always possible to determine what the errors were that resulted in failures if a subsequent retry passes. This is the case in flaky tests.
So to aid in resolving flaky tests the exception message for errors is added to printout as exampled below.
>/spec/lib/rspec/retry_spec.rb:43 1st Try error:
> 
>    expected false
>              got true
This is activated with the new setting variable: display_try_failure_messages. This variable is defaulted to false. It works in conjunction with verbose_retry. So the settings should be similar to below. 
```ruby
RSpec.configure do |config|
config.verbose_retry = true
config.display_try_failure_messages = true
end
```
The messages will not print if …
=> Added ability to print failure exceptions for retries in verbose output

lib/rspec/retry.rb, lib/rspec_ext/rspec_ext.rb, spec/lib/rspec/retry_spec.rb, spec/spec_helper.rb
This allows RSpec Retry to be invoked programmatically in an around hook by calling `ex.run_with_retry(opts)`, which allows the behavior to be more customizable. Custom retry options can be passed into this method. Example:
```ruby
config.around :each, :js do |ex|
ex.run_with_retry retry: 3
end
```
Fixes #20, #44
=> Refactor so that retry can be called programmatically

lib/rspec/retry.rb, lib/rspec/retry/formatter.rb
This adds the ability to print a retry report at the end of the test run by adding to the spec_helper:
``` ruby
RSpec.configure do |config|
config.add_formatter RSpec::Retry::Formatter
end
```
Summary will look like this:
```
Rspec::Retry::Formatter does the job
add random test failures in summary
counts passing tests in summary
counts failures in summary (FAILED - 1)
Removing DynamoDBLocal process
Failures:
1) Rspec::Retry::Formatter does the job counts failures in summary
Failure/Error: expect(0).to eq 1
expected: 1
got: 0
(compared using ==)
Finished in 0.98055 seconds (files took 2.98 seconds to load)
3 examples, 1 failure
Failed examples:
rspec ./spec/lib/status_spec.rb:188 # Rspec::Retry::Formatter does the job counts failures in summary
RSpec Retry Summary: …
```
=> Add formatter to print summary

README.md, lib/rspec/retry.rb, spec/lib/rspec/retry_spec.rb
Sometimes it's easier to specify an exclusion list of exceptions to retry on. For example, if my tests are failing because of permission errors, don't bother retrying (it only takes longer to run a bunch of failures). This change adds a config mechanism for an exclusion list, and defines how it interacts with the current inclusion list.
=> Add an exclusion filter for exceptions to retry

lib/rspec/retry.rb
I had a use case of `retry_count=2` and the error messages weren't displaying.
Given the above use case - when the first attempt fails: `attempts=1` (`attempts` initialize at 0 and increment after the example is ran) and `retry_count=2`. With these values, the `try_message` will not display given the old logic. 
In addition, with higher `retry_count` values - when displaying the `try_message` - it should mention the current `attempt` number as it is that attempt which failed (not the next).
=> BUGFIX: fix displaying of failure messages

lib/rspec/retry.rb, spec/lib/rspec/retry_spec.rb, spec/spec_helper.rb
RSpec has the ability to wrap multiple exceptions into one when running tests, this can come from either the new(ish) `aggregate_failures` functionality, or from errors arising in hooks in failing tests...
Rather than just plainly print these out it might be nicer to output each one.
=> Cope with multiple exceptions in an example

rspec-retry.gemspec
`<=3.5` is only allow `3.5.0`. I think the patch version of the update may be to be able to, how about?
=> allow to use rspec 3.5.x

lib/rspec/retry/formatter.rb
This is needed to use the --out flag with this formatter.
The output attr comes from the BaseFormatter https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/formatters/base_formatter.rb#L18
It defaults to stdout, but can be overriden on a per-formatter basis with the --out flag.
=> Print summary through output instead of always to STDOUT

rspec-retry.gemspec
I'm working on the open source project [VersionEye](https://www.versioneye.com). By adding the license info to the gempspec it becomes available through the public RubyGems API and that way other tools like VersionEye can fetch it easier.
=> Adding license info to the gemspec.

README.md, lib/rspec/retry.rb, spec/lib/rspec/retry_spec.rb
The idea is that there may be clean up tasks (besides flushing the `let`s). This would allow users to configure a block that would be run between each retry; for example flushing out the database).
```
RSpec.configure do |config|
config.retry_callback = proc do
puts "\n#### Forcing database truncation ####".cyan
DatabaseCleaner.clean_with(:truncation)
end
end
```
My use case is that by default a `transaction` database clean is used, however there are occasions where this falls over itself due to asynchronous resource locking where a spec succeeds but the DB resources are left behind.
Rather than switching for a full truncation method between specs, it would be much nicer if we could *somewhat* identify these and just run the full flush when needed.
Thoughts?
=> Add `retry_callback` to allow for custom cleanup between retries

lib/rspec/retry.rb, spec/lib/rspec/retry_spec.rb
The semantics of `rspec-retry`'s rescuing are a bit different than ruby's rescue. Ruby will rescue classes based on the case equality operator as well (`===`). [This blog post describes is very well](http://blog.honeybadger.io/level-up-ruby-rescue-with-dynamic-exception-matchers/)
With this PR, users will be able to dynamically retry on errors.
Let me know if you have any thoughts 😄
=> Add ability to match errors on case equality

.travis.yml, README.md, changelog.md, gemfiles/rspec_3.3.gemfile.lock, gemfiles/rspec_3.4.gemfile.lock, gemfiles/rspec_3.5.gemfile.lock, gemfiles/rspec_3.6.gemfile.lock, gemfiles/rspec_3.7.gemfile.lock, lib/rspec/retry/version.rb, rspec-retry.gemspec
@michaelglass This PR is to prevent builds from breaking when rspec-core upgrades. I think it would be preferable to add testing as new rspec versions come out, but not hard block the upgrade with a constraint.
=> Remove <3.8 constraint on rspec-core

lib/rspec/retry.rb, spec/lib/rspec/retry_spec.rb, spec/spec_helper.rb
The reason for this is to be able to skip retries on transactional tests which were causing DB deadlocks.
In our case only JS based tests fail randomly, so we use it this way:
```
config.retry_count_condition = ->(ex) { ex.metadata[:js] ? 3 : 1 }
```
=> Retry based on example metadata

lib/rspec/retry.rb, spec/lib/rspec/retry_spec.rb
replacement for https://github.com/NoRedInk/rspec-retry/pull/43
=> Aeberlin store attempted retries in example metadata

lib/rspec_ext/rspec_ext.rb, spec/lib/rspec/retry_spec.rb
This is useful for around/after hooks to check how many retries are actually attempted.
=> Expose RSpec::Core::Example#attempts via Procsy

lib/rspec/retry.rb, spec/lib/rspec/retry_spec.rb
The number of attempts is already exposed via `example.metadata[:retry_attempts]` but you can't get access to the actual spec failure exception. 
This PR exposes that through the metadata `example.metadata[:retry_exceptions]`.
=> Expose retry exceptions to example metadata

.travis.yml
travis couldn't find ruby 2.5.0 so loosened the patch specficiation
=> fix travis ruby versions and add ruby 2.6

rspec-retry.gemspec
This PR changes the gemspec to be more explicit: this gem exposes 0 executables.
=> gemspec: Expose 0 executables explicitly

rspec-retry.gemspec
This reduces unnecessary redirection from http://... to https://... when someone visits this gem's homepage via https://rubygems.org/gems/rspec-retry or some tools or APIs that use the gem's metadata.
=> GitHub is HTTPS by default
